### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by jfoliveira** [jalipert/elixir-tslint#1]
Hi, thanks for making this package publicly available.

I'm trying to use it as follows but is throwing the error

```
TypeError: Cannot read property 'output' of undefined
    at Stream.reportFailures (/Users/jeoliveira/ceviu/dev/src/ceviu-web/node_modules/elixir-tslint/node_modules/gulp-tslint/index.js:215:46)
    at Stream.stream.write (/Users/jeoliveira/ceviu/dev/src/ceviu-web/node_modules/elixir-tslint/node_modules/gulp-tslint/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
```

My `gulpfile.js`:

``` javascript
var elixir = require('elixir-tslint');

elixir(function(mix) {
    mix.tslint('resources/assets/typescript');
});
```

Could you give an example on how to use this package from `gulpfile.js`?

**Comment by jalipert** [comment]
Sorry, I created this project but never had the time to get it working myself.  If someone would like to take over the development, let me know.

**Comment by ghost** [comment]
I used this, and it's working.

```
Elixir.extend('tslint', function (src, options) {

    var paths = new Elixir.GulpPaths().src(src);

    new Elixir.Task('tslint', function () {

        return gulp.task("tslint", () =>
            gulp.src(src)
                .pipe(tslint(options || {}))
                .pipe(tslint.report({
                    emitError: false
                }))
                .on('error', function (e) {
                    new Elixir.Notification().error(e, 'TS Lint failed!');
                    this.emit('end');
                })
                .pipe(new Elixir.Notification('TS Lint succeeded!'))
        );
    }).watch(paths.src.path);
});
```

implementation:

```
   mix.tslint(['yourfiles','anotherone'],rules);
   // where rules comes from a config file.
```

for example:

```
{
  "formatter" : "prose",
  "rules": {
    "class-name": true,
    "comment-format": [true,
      "check-space"
    ],
    "indent": [true,
      "spaces"
    ],
    "one-line": [true,
      "check-open-brace",
      "check-whitespace"
    ],
    "no-var-keyword": true,
    "quotemark": [true,
      "double",
      "avoid-escape"
    ],
    "semicolon": true,
    "whitespace": [true,
      "check-branch",
      "check-operator",
      "check-separator",
      "check-type",
      "check-module"
    ],
    "typedef-whitespace": [true, {
      "call-signature": "nospace",
      "index-signature": "nospace",
      "parameter": "nospace",
      "property-declaration": "nospace",
      "variable-declaration": "nospace"
    }],
    "next-line": [true,
      "check-catch",
      "check-else"
    ],
    "no-internal-module": true,
    "no-trailing-whitespace": true,
    "no-inferrable-types": true,
    "no-null-keyword": true,
    "no-unused-variable": true,
    "boolean-trivia": true,
    "type-operator-spacing": true,
    "prefer-const": true,
    "no-in-operator": true,
    "no-increment-decrement": true,
    "object-literal-surrounding-space": true
  }
}
```
